### ISSUE TITLE
DO NOT DOWNLOAD .exe binary - CONTAINS MALWARE: "Wacatac"

### ISSUE THREAD

**Issue by GeldHades27355** [SafeBreach-Labs/WindowsDowndate#2]
![Screenshot 2024-08-30 154409](https://github.com/user-attachments/assets/7dc6c2c8-1a80-46a5-a176-38c1cc1dc25a)

Both free Windows Defender and Microsoft Defender for Endpoint (for M365) immediately detect and block the .exe.

So it doesn't work.

**Comment by 0xDeku** [comment]
Since the tool is public, security vendors are basing detections on it. This is not an issue with the tool.

**Comment by GeldHades27355** [comment]
Please explain.
1. Wacatac has been in MSFT signatures since 2022. How does that relate to this tool - which is supposedly new?
2. If this tool is designed to downdate Windows but is thwarted even by the standard/free Defender (also tested), what's the point of having the binary in the first place?

**Comment by 0xDeku** [comment]
The Wacatac classification is a mis-classification. Windows Defender detects PyInstaller executables as Wacatac sometimes, as you can see here - https://github.com/pyinstaller/pyinstaller/issues/5854

**Comment by GeldHades27355** [comment]
How does that change the fact that the binary does not work on Windows?

**Comment by GeldHades27355** [comment]
How utterly offensive. Is that the tone you want to set here? Really? Ok, so be it.

First of all, I'm talking about the BINARY .exe, not the source code. Just to be clear.

1. Looks like you, "my boy", and/or the team who released the binary is new to the filed - if you make a known mistake that renders the binary useless from the get-go by including software that blocks it from running on literally EVERY Windows device on the planet. 🤦
2. You're trying to prove a point - namely that you can hack Windows open again. Well it certainly won't work with the binary you provided. Just raises some concern whether you / the team know how Defender works.
3. You just proved my point. If this "hacktool" is blocked by basic Defender, it's not much of a hacktool, is it?

Here's what you COULD do:
build a binary that actually runs on Windows and then post back. In the meantime, I am telling every Windows expert I know that your binary does nothing.

Because you can argue all you want: the binary doesn't work. Hence, it's worth an issue reported here - which I did. Instead of addressing it, the team chose to bury it. 🤣

Truth be told, I was actually looking forward to testing this on our secured M365 tenant's joined Windows devices to see if and what sort of damage it can do.
But the only damage I can see to date is ZERO. Because you won't help folks actually repro your findings and reports.

This has been one of the most unprofessional engagements I've had with anyone in the cybersecurity biz - and that's saying a lot.

**Comment by je5442804** [comment]
> 太无礼了。这就是你想要在这里营造的氛围吗？真的吗？好吧，就这样吧。
> 
> 首先，我说的是二进制 .exe，而不是源代码。只是为了清楚起见。
> 
> 1. 看起来你，“我的孩子”，和/或发布二进制文件的团队对这个领域来说都是新手——如果你犯了一个已知的错误，从一开始就让二进制文件变得毫无用处，包括阻止它在地球上几乎每个 Windows 设备上运行的软件。🤦
> 2. 您正在试图证明一个观点 - 即您可以再次破解 Windows。好吧，它肯定不会与您提供的二进制文件一起使用。只是引起了一些担忧，您/团队是否知道 Defender 的工作原理。
> 3. 你刚刚证明了我的观点。如果这个“黑客工具”被基本 Defender 阻止，那么它就不算是一个黑客工具，不是吗？
> 
> 您可以这样做： 构建一个在 Windows 上实际运行的二进制文件，然后回发。与此同时，我告诉我认识的每一位 Windows 专家，您的二进制文件什么也不做。
> 
> 因为你可以随心所欲地争论：二进制文件不起作用。因此，值得在这里报告这个问题——我就是这么做的。团队没有解决这个问题，而是选择将其埋没。🤣
> 
> 说实话，我其实很期待在我们安全的 M365 租户加入的 Windows 设备上测试这一点，看看它是否会造成损害以及会造成什么样的损害。 但到目前为止，我看到的唯一损害是零。因为你不会帮助人们真正重现你的发现和报告。
> 
> 这是我与网络安全行业人士进行过的最不专业的接触之一，这说明了很多问题。

🤣👉🤡👈🗿

**Comment by GeldHades27355** [comment]
UPDATE:
1. Official Python Installers from https://www.python.org/downloads/release/python-3125/ work just fine. How come you're not using those?
2. Even the python source code will neither download, nor copy to nor open/execute on any Windows device tested.

As of now, this hack doesn't work - at all.

**Comment by 0xDeku** [comment]
The issue you're describing is common across nearly all offensive tools globally. There are several workarounds for static detections: you can recompile with PyInstaller to generate a new executable that won't be immediately flagged, run the Python source directly with an interpreter, obfuscate the files (either the source code or the compiled binaries) and more. However, these actions are beyond the scope of this repository and are the responsibility of the user to implement if desired. This approach aligns with industry standards for tools of this nature.

If you encounter any issues with the tool's functionality, please feel free to open additional issues.
