### ISSUE TITLE
windows_downdate.py can't be download, copied or executed on any Windows device at all

### ISSUE THREAD

**Issue by GeldHades27355** [SafeBreach-Labs/WindowsDowndate#4]
Now I tried to get around the issue of Windows Defender potentially recognizing the python installer included in .exe binary you provided by downloading the source code "windows_downdate.py" individually to run it within a legitimate Windows python runtime: https://www.python.org/downloads/release/python-3125/ (which installs just fine, btw)

Result: I am utterly unable to download or copy the file "windows_downdate.py" to ANY Windows device I tried.

Defender (even the free version) blocks any access to or any attempt to download it.

If you want folks to test your hack, you should provide other instructions on how to actually make it work.

**Comment by 0xDeku** [comment]
I could not repro this - 

![image](https://github.com/user-attachments/assets/2d2452f4-5699-4485-be5b-c762b97115a1)

Regardless, please see my [last comment](https://github.com/SafeBreach-Labs/WindowsDowndate/issues/2#issuecomment-2335140697) on the other issue you opened regarding static detections.

And again, If you encounter any issues with the tool's functionality, please feel free to open additional issues.
