### ISSUE TITLE
Python setuptools missing from repo - usage instructions / documentation is incorrect

### ISSUE THREAD

**Issue by GeldHades27355** [SafeBreach-Labs/WindowsDowndate#5]
Python setuptools is missing from the repo and the instructions do not indicate they need to be installed manually.

Please either add setuptools to the repo or add a step to manually install setuptools first.

**Comment by 0xDeku** [comment]
I have added new installation steps and setuptools is no longer used, please follow the new installation steps to install the tool and let me know if you encounter issues.
