### ISSUE TITLE
requirements.txt contains syntax errors - install fails

### ISSUE THREAD

**Issue by GeldHades27355** [SafeBreach-Labs/WindowsDowndate#6]
requirements.txt contains

```
pywin~=306
setuptools~=69.1.1
psutil~=5.9.8

```

That fails during install.

it _should_ be:

```
pywin>=306
setuptools>=69.1.1
psutil>=5.9.8

```

**Comment by 0xDeku** [comment]
Thanks for opening the issue, fixed [here](https://github.com/SafeBreach-Labs/WindowsDowndate/pull/10)
