### ISSUE TITLE
Python win32security missing from repo - usage instructions / documentation is incorrect

### ISSUE THREAD

**Issue by GeldHades27355** [SafeBreach-Labs/WindowsDowndate#7]
Repo does not contain this module - execution fails without it.

fixes:
1. add a manual install instruction to https://github.com/SafeBreach-Labs/WindowsDowndate/tree/main/examples/VBS-UEFI-Locks-Bypass
2. include in repo

**Comment by 0xDeku** [comment]
I could not repro this. Please follow the installation instructions, win32security should not be missing. Let me know if you encounter issues.
