### ISSUE TITLE
component_store_utils.py references "win32security", which doesn't exist. It is called "Win32Security"

### ISSUE THREAD

**Issue by GeldHades27355** [SafeBreach-Labs/WindowsDowndate#8]
examples/VBS-UEFI-Locks-Bypass/Config.xml fails because component_store_utils.py references `win32security`, which doesn't exist.

After manually installing it with pip install win32security, pip list shows it as "Win32Security".

**Comment by GeldHades27355** [comment]
My bad. Path isnt set correctly.

**Comment by GeldHades27355** [comment]
my bad. path isnt set correctly.

**Comment by 0xDeku** [comment]
I could not repro this. Win32Security and win32security are not the same modules - 
[Win32Security](https://pypi.org/project/Win32Security/)
[Pywin32's win32security](https://pypi.org/project/Win32Security/)

![image](https://github.com/user-attachments/assets/67158593-93e3-4cc2-8b72-267b37071ea4)

Please follow the installation instructions, win32security should not be missing. Let me know if you encounter issues.

**Comment by GeldHades27355** [comment]
Didnt think they were - since Python is case sensitive.

So here's my system:

[](C:\Program Files\Python312\Scripts>python -m pip install pywin32
DEPRECATION: Loading egg at c:\program files\python312\lib\site-packages\psutil-6.0.0-py3.12-win-amd64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at
https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\program files\python312\lib\site-packages\windowsdowndate-1.0-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at
https://github.com/pypa/pip/issues/12330
Requirement already satisfied: pywin32 in c:\program files\python312\lib\site-packages (306))
