### ISSUE TITLE
Example: Kernel-Suite-Downgrade fails

### ISSUE THREAD

**Issue by GeldHades27355** [SafeBreach-Labs/WindowsDowndate#9]
After spending hours closing the gaps in the documentation and fixing syntax errors in some of the code (as a non-Python expert), am getting this result:

```
C:\Temp\WindowsDowndate>python windows_downdate.py --config-xml examples/Kernel-Suite-Downgrade/Config.xml
[INFO] Starting Windows-Downdate
Traceback (most recent call last):
  File "C:\Temp\WindowsDowndate\windows_downdate.py", line 327, in <module>
    main()
  File "C:\Temp\WindowsDowndate\windows_downdate.py", line 306, in main
    update_files = parse_config_xml(args.config_xml)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Temp\WindowsDowndate\windows_downdate.py", line 222, in parse_config_xml
    update_file_obj = UpdateFile(source_file, destination_file)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Temp\WindowsDowndate\windows_downdate.py", line 39, in __init__
    self._source_path_obj = PathEx(source_path)
                            ^^^^^^^^^^^^^^^^^^^
  File "C:\Temp\WindowsDowndate\windows_downdate\filesystem_utils.py", line 25, in __new__
    self = cls._from_parts(args)
           ^^^^^^^^^^^^^^^
AttributeError: type object 'PathEx' has no attribute '_from_parts'. Did you mean: '_load_parts'?
```

I'm happy to be wrong about something in my Python setup - but this looks more like a code problem.

The Config.xml is unmodified.

PS. All other examples also fail with similar errors.

**Comment by 0xDeku** [comment]
I could not repro this, but just pushed installation fixes. Make sure you pull from main and then follow installation steps. In addition, when using examples make sure you target the correct Windows version as listed in the example's readme.

I will be closing this issue for now, feel free to re-open if you encounter issues.

**Comment by JadonW01** [comment]
DID you ever fix this @GeldHades27355 
> Make sure you pull from main and then follow installation steps. In addition, when using examples make sure you target the correct Windows version as listed in the example's readme.
> 
> I will be closing this issue for now, feel free to re
